version: "3.2"

services:
    php:
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: ${APP_NAME:?err}-php
        volumes:
            - .:/var/www/html/:cached

    nginx:
        image: nginx:latest
        container_name: ${APP_NAME:?err}-nginx
        ports:
            - 8012:80
            - 443:443
        links:
            - 'php'
        volumes:
            - .:/var/www/html/
            - ./docker/nginx:/etc/nginx/conf.d
